// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace EFCoreEqualNotDefinedDemo
{
    public partial class BloggingContextModel
    {
        partial void Initialize()
        {
            var blog = BlogEntityType.Create(this);

            BlogEntityType.CreateAnnotations(blog);

            AddAnnotation("ProductVersion", "7.0.0-preview.4.22229.2");
        }
    }
}
